version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    platform: linux/amd64
    image: xxxziiko/findyourkicks-admin
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - ./apps/admin/.env.production:/workspace/apps/admin/.env.production