name: CD - Shop App Deploy

on:
  repository_dispatch:
    types: [deploy-shop]
  workflow_dispatch:
    
env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_SHOP: ${{ secrets.DOCKERHUB_SHOP }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with: 
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ env.DOCKER_USERNAME }}/${{ env.DOCKERHUB_SHOP }}:latest
            sudo docker stop ${{ env.DOCKERHUB_SHOP }}
            sudo docker rm ${{ env.DOCKERHUB_SHOP }}
            sudo docker run -d --name ${{ env.DOCKERHUB_SHOP }} -p 3001:3001 ${{ env.DOCKER_USERNAME }}/${{ env.DOCKERHUB_SHOP }}:latest
