name: CI - Docker Build and Push Changed Apps

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKERHUB_ADMIN: ${{ secrets.DOCKERHUB_ADMIN }}
  DOCKERHUB_SHOP: ${{ secrets.DOCKERHUB_SHOP }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
  API_URL: ${{ secrets.API_URL }}
  ADMIN_BASE_URL: ${{ secrets.ADMIN_BASE_URL }}
  

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      shop_changed: ${{ steps.filter.outputs.shop }}
      admin_changed: ${{ steps.filter.outputs.admin }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect Changed Apps
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            # shop:
            #   - 'apps/shop/**'
            #   - 'packages/shared/**'
            admin:
              - 'apps/admin/**'
              - 'packages/shared/**'
              - '.github/workflows/**'
              


  # build-and-push-shop:
  #   needs: [detect-changes]
  #   if: needs.detect-changes.outputs.shop_changed == 'true'

  build-and-push-admin:
    needs: [detect-changes]
    if: needs.detect-changes.outputs.admin_changed == 'true'
    runs-on: ubuntu-latest
      
    steps:
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/admin/Dockerfile
          push: true
          platform: linux/amd64
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKERHUB_ADMIN }}:latest
          no-cache: true
          build-args: |
            VITE_SUPABASE_URL=${{ env.SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ env.SUPABASE_ANON_KEY }}
            VITE_API_URL=${{ env.API_URL }}
            VITE_ADMIN_BASE_URL=${{ env.ADMIN_BASE_URL }}
          
      - name: Trigger CD
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.GH_TOKEN }}
          event-type: deploy-admin
